In [40]:
!pip install numpy pandas

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [41]:
import pandas as pd
import numpy as np

In [42]:
df = pd.DataFrame(
    {
        "Student Name" : ["Nikhil","Sreyas","Pardheev"],
        "Age" : [20,np.nan,19],
        "Gender": ['M',np.nan,'M'],
        "Department": ['CSE','CSE',np.nan]
    }
    )

In [43]:
df

  Student Name   Age Gender Department
0       Nikhil  20.0      M        CSE
1       Sreyas   NaN    NaN        CSE
2     Pardheev  19.0      M        NaN

In [44]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df

  Student Name   Age Gender Department
0       Nikhil  20.0      M        CSE
1       Sreyas  19.5    NaN        CSE
2     Pardheev  19.0      M        NaN

In [45]:
df['Department'] = df['Department'].ffill()
df

  Student Name   Age Gender Department
0       Nikhil  20.0      M        CSE
1       Sreyas  19.5    NaN        CSE
2     Pardheev  19.0      M        CSE

In [46]:
df['Gender'] = df['Gender'].bfill()
df

  Student Name   Age Gender Department
0       Nikhil  20.0      M        CSE
1       Sreyas  19.5      M        CSE
2     Pardheev  19.0      M        CSE